spring.datasource.password=mEP*DJZ/EXApB9s
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres?user=postgres.ehwmecpbgnitulxrcbcp&password=mEP*DJZ/EXApB9s
spring.mail.password=yehn evml wwdm awnk